// <auto-generated />
using System;
using Hephaestus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hephaestus.Migrations
{
    [DbContext(typeof(HephaestusContext))]
    partial class HephaestusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hephaestus.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtsAndOrationDie");

                    b.Property<int>("BloodAndValorDie");

                    b.Property<int>("CraftAndReasonDie");

                    b.Property<string>("Epithet")
                        .IsRequired();

                    b.Property<int>("EpithetDie");

                    b.Property<string>("FavorGodName1");

                    b.Property<string>("FavorGodName2");

                    b.Property<string>("FavorGodName3");

                    b.Property<string>("FavorGodName4");

                    b.Property<int>("FavorScore1");

                    b.Property<int>("FavorScore2");

                    b.Property<int>("FavorScore3");

                    b.Property<int>("FavorScore4");

                    b.Property<string>("HonoredGod");

                    b.Property<bool>("IsDemigod");

                    b.Property<string>("Lineage");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NameDie");

                    b.Property<string>("Notes");

                    b.Property<string>("Pronouns");

                    b.Property<int>("ResolveAndSpiritDie");

                    b.Property<string>("Strength");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Hephaestus.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hephaestus.Models.Hero", b =>
                {
                    b.HasOne("Hephaestus.Models.User")
                        .WithMany("UserHeroes")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
